name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 💡
        
        Before submitting, please search for existing feature requests to avoid duplicates.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: Alternatively, we could...

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - UI/UX Enhancement
        - AI/ML Feature
        - API Enhancement
        - Performance Improvement
        - Security Feature
        - Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my usage
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. As a user, I want to...
        2. When I'm working on...
        3. During the process of...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: Any mockups, examples, or references that help explain the feature
      placeholder: Attach images or provide links to examples

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: Any ideas on how this could be implemented (optional)
      placeholder: This could be implemented by...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests before submitting
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: I would be willing to help implement this feature
          required: false